version: '3.8'
name: ciberfinal

services:
  product-api:
    image: ciberfinal-product.api:latest
    container_name: ${PRODUCT_API_HOST}
    build:
      context: ./Api.Products
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=${MSSQL_HOST};Database=${MSSQL_PROD_DATABASE};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5001:80"
    depends_on:
      - mssql-db

  eshop-app:
    image: ciberfinal-eshop.app:latest
    build:
      context: ./App.eShop
    environment:
      NG_APP_PRODUCTS_URL: http://localhost:5001
    volumes:
      - ./App.eShop:/app
    ports:
      - "8547:4200"
      - '49153:49153'
    depends_on:
      - product-api
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ${MSSQL_HOST}
    ports:
      - '${MSSQL_PORT}:1433'
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_DATA_DIR: /var/opt/sqlserver/data
      MSSQL_LOG_DIR: /var/opt/sqlserver/log
      MSSQL_BACKUP_DIR: /var/opt/sqlserver/backup
    volumes:
      - sql-server-data:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup: